### PR TITLE
Add python-pip, CentOS installation to documentation

### PR DESCRIPTION
**Pull request by jessek**
You must have pip installed to use pip, so I've added to the list of required packages.

### CODE REVIEW

**Comment by jessek** [comment]
Added instructions for CentOS installation

**Comment by marnao** [comment]
Jesse,

Thanks for the updates. Much appreciated.

I assume you tested this on EL7, not EL6? Would you mind clarifying in your notes?

One thing I noticed in reviewing your instructions is that the zeromq package from EPEL differs greatly from EL6 (version 2.x) to EL7 (version 4.x). The zeromq3 package (which is what we use) remains more consistent. I don't think this is an issue since there is supposed to be compatibility across all 3 of these versions per http://zeromq.org/intro:get-the-software . Not recommending a change at this point, but the lack of testing is something to be aware of.

**Comment by jessek** [comment]
Thanks for the feedback. In all honesty, I have not tested the code which exercises the zeromq functionality. I'd have no problem changing the package to zeromq3.

I tested this procedure on one of our CentOS systems, not a vanilla install, running 7.1.1503. My test procedure was to create a zip of binaries and run python laika.py on it. Minimal to be sure, but I figured that having **some** instructions for CentOS would be better than none.

**Comment by jessek** [comment]
Truth be told, I'm not sure either one of those packages contains the Python bindings for ZeroMQ.

**Comment by marnao** [comment]
Ah yes-- I missed that. You're going to want python-zmq from EPEL. It should work with any version of zeromq.

And yes, I agree, some instructions are better than none. Thanks for taking the time.

**Comment by marnao** [comment]
Thanks again.

**Pull request merged**
