### PR TITLE
Fixed broken pefile link

### PR DESCRIPTION
**Pull request by estuart**
This addresses issue #45

### CODE REVIEW

**Comment by knowmalware** [comment]
I suggest using the archive from the official repo on github:
  https://github.com/erocarrera/pefile/archive/pefile-1.2.10-139.zip

**Review by estuart — COMMENTED** [review]
Changing from broken PE file link to github hosted google code archive link

**Comment by knowmalware** [comment]
You forgot to change the sha256 and the other references to the tarball.  If it is easier, use the tarball URL instead of the ZIP url:
  https://github.com/erocarrera/pefile/archive/pefile-1.2.10-139.tar.gz

I also just tried installing from that URL, and looks like the __version__ variable is not being set properly.  I suggest adding these lines right before you unpack the tarball:

``` bash
cat pefile.py | sed 's/^__version__ = .*$/__version__ = "1.2.10-139"/' > pefile-fixed.py
mv pefile-fixed.py pefile.py
```

**Comment by marnao** [comment]
Fixed in #68

**Pull request closed without merging**
