### PR TITLE
Improve README readability

### PR DESCRIPTION
**Pull request by mmattioli**
Improve the markdown formatting of `README.md` so that it's more clearly organized and readable.

### CODE REVIEW

**Comment by marnao** [comment]
Thanks for your contributions @mmattioli!

According to the FSF, updating the copyright notices on a yearly basis is not the correct thing to do. They should only be updated (by appending the current year) when a modification has been made to a publication. Otherwise when the publication remains unchanged, the copyright notice for the original publication year would remain indefinitely.

see: https://www.gnu.org/licenses/gpl-howto.html

If you could create another pull request with just your formatting changes I would be glad to review that.

**Comment by mmattioli** [comment]
@marnao if you re-open this PR you will be able to see that I updated the branch which I used to base this PR with just the formatting commit

**Comment by mmattioli** [comment]
@marnao any update?

**Comment by marnao** [comment]
Unfortunately the "reopen" button is not available.. I've never done that before so it's possible I'm missing something. It says "the docfixes branch was force-pushed or recreated"..

Would you mind creating a new pull request?

**Pull request closed without merging**
