### PR TITLE
Major meta_pe refactor

### PR DESCRIPTION
**Pull request by mtmcgrew**
- refactor meta_pe to use more built in features of pefile
- More metadata (eg. more details about resources)

### CODE REVIEW

**Comment by marnao** [comment]
We have some unreleased changes to META_PE that possibly overlap with yours. We'll have to take a look to see how they match up. Stay tuned.

p.s. it looks like your IPv6 commit snuck in here.

**Comment by mtmcgrew** [comment]
Cool, looking forward to it. gah, I thought I took care of the v6 commit in this branch. 

edit: Yes i did take care of it, it was reverted with the "new branch" commit.

**Comment by marnao** [comment]
my fault. missed the revert!

**Comment by marnao** [comment]
We are curious to know if you've observed any differences between calculating the rich hashes on the "raw data" vs the "clear data". I see you chose to calculate yours on the "clear data". Yara's PE module of course gives you access to both. Have you ever observed the XOR key value (checksum) changing while the rich signature stays the same (yielding a different rich hash)?

Let me know if you'd prefer to take this conversation private.

**Comment by mtmcgrew** [comment]
No, I don't have a strong preference either way on that one.

**Comment by marnao** [comment]
I've completed testing and everything looks great. Very much appreciate the simplification and additional data you added. 

A note to other users:

The biggest change here aside from the addition of new data is the previously hardcoded values are now using pefile's native naming convention.

For instance, here's one example:
$ diff <(jq '.scan_result[0] | .moduleMetadata.META_PE."Image Characteristics"' scan_meta.old) <(jq '.scan_result[0] | .moduleMetadata.META_PE."Image Characteristics"' scan_meta.new)
2,6c2,6
 <   "RELOCS_STRIPPED",
 <   "EXECUTABLE_IMAGE",
 <   "LINE_NUMS_STRIPPED",
 <   "LOCAL_SYMS_STRIPPED",
 <   "32BIT_MACHINE"
 ---
 >   "IMAGE_FILE_LOCAL_SYMS_STRIPPED",
 >   "IMAGE_FILE_32BIT_MACHINE",
 >   "IMAGE_FILE_EXECUTABLE_IMAGE",
 >   "IMAGE_FILE_LINE_NUMS_STRIPPED",
 >   "IMAGE_FILE_RELOCS_STRIPPED"

The names now include the appropriate prefixes. Not a huge change, just something to be aware of.

**Pull request merged**
