### PR TITLE
adding manifest file parsing module

### PR DESCRIPTION
**Pull request by jshlbrd**
This PR adds a JAR manifest file parsing module. The module relies on python-javatools. Thanks!

### CODE REVIEW

**Comment by jshlbrd** [comment]
Sample output can be seen here: https://github.com/jshlbrd/laikaboss-modules/tree/master/meta_manifest

**Comment by kglm** [comment]
Nice and simple, beautiful module. Got one recommendation and two suggestions for you.

Recommend: You add the name JAVA to the module name. This provides more context at the global scope for the type of manifest being meta'd. Since you are using javatool's Manifest parser, I assume this is specific to JAR manifests and isn't necessarily reliable for other INF manifest files (didn't do much homework here).

Suggest: You can import and except ScanError instead of having to do all three framework exceptions (QuitScanException, GlobalScanTimeoutError, GlobalModuleTimeoutError). These exceptions inherit ScanError, so ScanError handles them all. This was an addition after several modules were developed, betting you just copy-pasted from one of these old ones (as you should, don't reinvent the wheel).

Suggest: We have tried to stick with 4 space indentations. I noticed the scan_module line in the Yara dispatch rule uses a tab.

**Comment by jshlbrd** [comment]
Good feedback-- I'll update this soon. Thanks!

**Comment by jshlbrd** [comment]
All updated-- let me know if you see any other issues. Thanks!

**Comment by kglm** [comment]
Looks good. I must have overlooked the fact that the try-except is superfluous here since there isn't any exceptional cases, but no harm is done really. Feel free to remove it if you want, if not we will merge it in after a few days.

**Comment by jshlbrd** [comment]
Fixed, thanks for the clarification.

**Pull request merged**
