### PR TITLE
README formatting and styling improvements

### PR DESCRIPTION
**Pull request by mmattioli**
Improved the formatting and styling of README.md for the sake of
organization and readability

### CODE REVIEW

**Comment by mmattioli** [comment]
@marnao here's the new PR that succeeds #57

**Comment by mmattioli** [comment]
@marnao, any update? 😁

**Comment by marnao** [comment]
is it just me or do the numbered lists, when rendered, only contain 1's?

**Comment by mmattioli** [comment]
@marnao I adjusted the syntax, simply needed an indent on the code blocks that were nested in the lists for the renderer to recognize it.

**Comment by mmattioli** [comment]
@marnao ?

**Comment by marnao** [comment]
Thanks for the contribution and sorry for the delay.

**Pull request merged**
