### PR TITLE
Create docker-compose.yml file and update image during build

### PR DESCRIPTION
**Pull request by ecstatic-nobel**
If Docker Compose is installed, images, containers, and volumes can all be built and managed using the docker-compose command.

Also, while building the image using the Dockerfile, I received the following error:
`E: Unable to locate package software-properties-common`

Running `apt-get update` retrieves a new list of packages and resolves the issue with the error mentioned above. Running `apt-get upgrade -y` will upgrade currently installed packages if upgrades are available.

### CODE REVIEW

**Comment by marnao** [comment]
I don't much experience with docker but this looks ok to me. @wzod any thoughts from you?

**Comment by wzod** [comment]
Nice addition with Docker Compose! I think the addition provides more opportunities for creating, deploying and testing multiple instances of Laika BOSS and may help users with testing new developments to the framework. 

Having said that, I have some concerns with available documentation for using Docker Compose as there may be additional steps involved depending on the operating system (e.g. Linux-based distributions will need to add an additional repository, modify their sources file and pull the latest build from GitHub while Windows/OS X users may have Docker Compose included as part of the installation package). Given the additional steps involved to install Docker Compose (compared to simply installing Docker from distribution repository or installation file), there may be a need to include some documentation/references to ensure others have no issue with setting up Docker Compose. A simple solution may be to provide links for additional information and possibly providing more details in the Docker Compose YAML file.

Lastly, I submitted a PR to address the issue with installing software-common-properties package due to a recent change with the base Ubuntu image provided by Docker. The change should resolve the need to update the Dockerfile.

Hope this helps!

**Comment by ecstatic-nobel** [comment]
@wzod Thanks for the advice. I added some more information to the docker-compose.yml file. Hopefully it's sufficient enough. The goal was to have the configuration options to mirror the original `docker run` command in the Dockerfile. I did add a links to the installation page and Compose file reference.

**Comment by marnao** [comment]
@leunammejii can you resolve the conflict with Dockerfile and I'll get this merged in? Sorry for the delay.

**Comment by ecstatic-nobel** [comment]
@marnao All conflicts have been resolved.

**Pull request merged**
